apiVersion: apps/v1
kind: Deployment
metadata:
  name: solar-backend
  namespace: solar-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-backend
  template:
    metadata:
      labels:
        app: solar-backend
    spec:
      containers:
      - name: solar-backend
        image: your-docker-registry/solar-backend:latest
        env:
        - name: MONGO_URI
          value: mongodb://mongo-svc:27017/solarapp
        - name: JWT_SECRET
          value: verysecret
        ports:
        - containerPort: 4000
