apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: timer-tools

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app: timer-tools
  managed-by: kustomize

